name: Spell checking
on: [pull_request, push]

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 0
    - uses: actions/checkout@v2.0.0
      with:
        path: .git/spell-check
        ref: spelling-data-lorem
    - uses: ./
      env:
        bucket: .git
        project: spell-check
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEBUG: 1
